name: Update ECS Service

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get install -y awscli

    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster fartgate-photon360-cluster --service fargate-photon360-service --force-new-deployment --region us-west-1
      env:
        AWS_ACCESS_KEY_ID: AKIAUZFNA2WLZNWL6UMF
        AWS_SECRET_ACCESS_KEY: 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

